#ifndef _ASM_SPARC_IOCTLS_H
#define _ASM_SPARC_IOCTLS_H

#include <uapi/asm/ioctls.h>

#define TIOCGETC __TIOCGETC
#define TIOCGETP __TIOCGETP
#define TIOCGLTC __TIOCGLTC
#define TIOCSLTC __TIOCSLTC
#define TIOCSETP __TIOCSETP
#define TIOCSETN __TIOCSETN
#define TIOCSETC __TIOCSETC
#endif /* !(_ASM_SPARC_IOCTLS_H) */
Tue Jul 19 12:41:57 PDT 2016
Fri Jul 22 15:53:14 PDT 2016
Sun, Jul 24, 2016  3:06:43 PM
