/* This file is automatically generated.  Do not edit. */
static const char *initial_sid_to_string[] =
{
    "null",
    "kernel",
    "security",
    "unlabeled",
    "fs",
    "file",
    "file_labels",
    "init",
    "any_socket",
    "port",
    "netif",
    "netmsg",
    "node",
    "igmp_packet",
    "icmp_socket",
    "tcp_socket",
    "sysctl_modprobe",
    "sysctl",
    "sysctl_fs",
    "sysctl_kernel",
    "sysctl_net",
    "sysctl_net_unix",
    "sysctl_vm",
    "sysctl_dev",
    "kmod",
    "policy",
    "scmp_packet",
    "devnull",
};

Tue Jul 19 12:34:39 PDT 2016
Fri Jul 22 15:39:36 PDT 2016
Sun, Jul 24, 2016  1:27:38 PM
Mon, Jul 25, 2016  6:37:21 PM
Mon, Jul 25, 2016  7:50:15 PM
Tue, Jul 26, 2016  2:25:32 PM
